# Generated by Django 4.1.7 on 2023-04-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Complete', models.BooleanField(default=False)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
