# Generated by Django 4.1.7 on 2023-04-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_uaready_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uaready',
            old_name='Webiste_URL',
            new_name='Website_URL',
        ),
    ]
