# Generated by Django 4.1.7 on 2023-04-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_webiste_url_uaready_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='Languages',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.uaready'),
        ),
    ]
