# Generated by Django 4.1.7 on 2023-04-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_languages_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uaready',
            name='Languages',
        ),
    ]
