# Generated by Django 4.1.7 on 2023-04-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_uaready_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='Language_Related_To',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='Language_Url',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='Languages',
        ),
        migrations.AddField(
            model_name='languages',
            name='Language_Title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='UAReady',
        ),
    ]
