# Generated by Django 4.1.7 on 2023-04-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_languages_language_related_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language_Title', models.CharField(default='', max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
