# Generated by Django 4.1.7 on 2023-04-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_language_delete_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAWebiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website_Title', models.CharField(max_length=500)),
                ('Webiste_URL', models.CharField(max_length=500)),
                ('Webiste_Language', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.language')),
            ],
        ),
    ]
